# Generated by Django 3.2.7 on 2021-10-06 12:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('senseikuApp', '0002_auto_20210930_2328'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('day', models.CharField(max_length=100)),
                ('hour', models.TimeField()),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='senseikuApp.course')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('review', models.CharField(max_length=1000)),
                ('rating', models.FloatField(default=0.0)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='senseikuApp.course')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
