# Generated by Django 3.2.7 on 2021-10-14 13:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('senseikuApp', '0003_review_schedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='tutor_id',
        ),
        migrations.AddField(
            model_name='course',
            name='tutor_username',
            field=models.ForeignKey(db_column='username', default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
    ]
