# Generated by Django 3.2.7 on 2021-10-14 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senseikuApp', '0004_auto_20211014_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='day',
            field=models.CharField(default='Senin', max_length=100),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='hour',
            field=models.CharField(default='7:30', max_length=100),
        ),
    ]
