# Generated by Django 3.2.7 on 2021-11-02 06:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('senseikuApp', '0010_auto_20211026_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracker',
            name='timestamp',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('timestamp', models.IntegerField()),
                ('username', models.ForeignKey(db_column='username', default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
        ),
    ]
