# Generated by Django 3.2.8 on 2021-11-09 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('senseikuApp', '0015_cart_total_course_price'),
        ('senseikuApp', '0016_alter_location_id'),
    ]

    operations = [
    ]
