# Generated by Django 3.2.8 on 2021-11-09 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senseikuApp', '0017_merge_20211109_1038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='total_course_price',
        ),
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.CharField(default='not verified', max_length=100),
        ),
    ]
