# Generated by Django 3.2.8 on 2021-11-09 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senseikuApp', '0020_auto_20211109_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='phone_number',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
