# Generated by Django 3.2.8 on 2021-11-09 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senseikuApp', '0022_cart_checked_out'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='checked_out',
        ),
        migrations.AddField(
            model_name='cart',
            name='time_checked_out',
            field=models.IntegerField(null=True),
        ),
    ]
