# Generated by Django 3.1.3 on 2021-10-21 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senseikuApp', '0006_auto_20211019_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='hour_finish',
            field=models.CharField(default='9:30', max_length=100),
        ),
    ]
