# Generated by Django 3.1.3 on 2021-10-24 14:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('senseikuApp', '0008_tracker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='course_id',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='day',
        ),
        migrations.AddField(
            model_name='schedule',
            name='availability',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='date',
            field=models.CharField(default='01-01-1970', max_length=100),
        ),
        migrations.AddField(
            model_name='schedule',
            name='tutor_username',
            field=models.ForeignKey(db_column='username', default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('num_meetings', models.IntegerField()),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='senseikuApp.course')),
                ('schedule_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='senseikuApp.schedule')),
                ('student_username', models.ForeignKey(db_column='username', default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
        ),
    ]
