# Generated by Django 3.1.3 on 2021-11-09 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senseikuApp', '0014_auto_20211109_1513'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='total_transport_price',
            new_name='transport_price',
        ),
        migrations.AddField(
            model_name='cart',
            name='course_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cart',
            name='total_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='location',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
